# Generated by Django 4.2.5 on 2023-09-28 20:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='آخر آماء خوانة'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('یش نویس', 'پیش نویس'), ('منتشر شده', 'منتشر شده'), ('رد شده', 'رد شده')], default='یش نویس', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('یش نویس', 'پیش نویس'), ('منتشر شده', 'منتشر شده'), ('رد شده', 'رد شده')], default='یش نویس', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=250, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=200, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(max_length=200, verbose_name='کشور'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=200, verbose_name='حذف توسطِ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='deleted_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='دلیل حذف'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(max_length=200, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('کم', 'کم'), ('متوسط', 'متوسط'), ('بالا', 'بالا')], default='متوسط', max_length=20, verbose_name='اولویت'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('باز', 'باز'), ('بسته', 'بسته'), ('درحال بررسی', 'درحال بررسی')], default='باز', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='blog.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='blog.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/ticket_attachments/', verbose_name='پیوست')),
                ('alt', models.CharField(blank=True, max_length=250, verbose_name='متن جایگزین')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('deleted_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ حذف')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_attachments', to='blog.ticket')),
            ],
            options={
                'verbose_name': 'پیوست',
                'verbose_name_plural': 'پیوست ها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='blog_ticket_created_c1b878_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, quality=75, scale=None, size=[500, 500], upload_to='media/profile_images', verbose_name='تصویر پروفایل')),
                ('alt', models.CharField(blank=True, max_length=250, verbose_name='متن جایگزین')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('deleted_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ حذف')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_images', to='blog.profile', verbose_name='پروفایل')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='blog_profil_created_ebfa65_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, quality=75, scale=None, size=[500, 500], upload_to='media/post_images', verbose_name='تصویر پست')),
                ('alt', models.CharField(blank=True, max_length=250, verbose_name='متن جایگزین')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('deleted_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ حذف')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='blog.post', verbose_name='پروفایل')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='blog_postim_created_26f197_idx')],
            },
        ),
    ]
