# Generated by Django 4.2.5 on 2023-09-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_post_image_remove_profile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی پست ها', 'verbose_name_plural': 'دسته بندی های پست ها'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'کامنت پست ها', 'verbose_name_plural': 'کامنت های پست ها'},
        ),
        migrations.AlterModelOptions(
            name='postimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'تصویر پست ها', 'verbose_name_plural': 'تصاویر پست ها'},
        ),
        migrations.AlterModelOptions(
            name='profileimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'تصویر پروفایل', 'verbose_name_plural': 'تصاویر پروفایل'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'برچسب پست ها', 'verbose_name_plural': 'برچسب های پست ها'},
        ),
        migrations.AlterModelOptions(
            name='ticketattachment',
            options={'ordering': ['-created_at'], 'verbose_name': 'پیوست تیکت ها', 'verbose_name_plural': 'پیوست های تیکت ها'},
        ),
    ]
