# Generated by Django 4.2.5 on 2023-10-09 08:36

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image_file',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, quality=75, scale=None, size=[500, 500], upload_to='blog_post_img/', verbose_name='تصویر پست'),
        ),
    ]
