# Generated by Django 4.2.5 on 2023-10-09 13:20

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_postimage_image_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='description',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='image_file',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, quality=75, scale=None, size=[500, 500], upload_to='profile_img/', verbose_name='تصویر پروفایل'),
        ),
    ]
